### ISSUE TITLE
add link to 2dii website to this readme

### ISSUE THREAD

**Issue by jacobvjk** [2DegreesInvesting/demo#6]
Whenever I read the readme, I feel terribly lost and think "If only I had a link to the 2dii homepage now"..
Could we add one? Tis would be helpful for many people.

**Comment by maurolepore** [comment]
Sounds like a great idea. @daisy-pacheco can you work on this?

**Comment by daisy-pacheco** [comment]
Sure! I will be happy to help!

**Comment by maurolepore** [comment]
Awesome! Thanks @jacobvjk and @daisy-pacheco! We are done with the demo so I'll go ahead and close this issue now.
